name: Call common build and push

on:
  push:
    branches: [ "main" ]
    
permissions:
  actions: write
  checks: write
  pull-requests: write
  statuses: read
  contents: read
 
jobs:
  call-pushworkflow:
    uses: dynamicweb/Common.Actions/.github/workflows/common-nuget-push.yml@main
    secrets:
      NUGETAPI: ${{secrets.NUGETAPI}}
